# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensed.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensed.proto',
  package='',
  serialized_pb='\n\x0csensed.proto\":\n\x06Sensed\x12\x11\n\ttimestamp\x18\x01 \x02(\x05\x12\x0c\n\x04\x66low\x18\x02 \x02(\x05\x12\x0f\n\x07\x62\x61ttery\x18\x03 \x02(\x05')




_SENSED = _descriptor.Descriptor(
  name='Sensed',
  full_name='Sensed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Sensed.timestamp', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flow', full_name='Sensed.flow', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battery', full_name='Sensed.battery', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['Sensed'] = _SENSED

class Sensed(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SENSED

  # @@protoc_insertion_point(class_scope:Sensed)


# @@protoc_insertion_point(module_scope)
