/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Fri Oct  6 12:36:54 2017. */

#include "sensed.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Sensed_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Sensed, timestamp, timestamp, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Sensed, flow, timestamp, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, Sensed, battery, flow, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
